main: add_binary.o stack.o
	gcc -g -Wall -pedantic -o main add_binary.o stack.o

stack.o: stack.c
	gcc -g -Wall -pedantic -c stack.c

addbi_nary.o: add_binary.c stack.h
	gcc -g -Wall -pedantic -c add_binary.c