####################################################
CC = gcc
CFLAGS = -g -Wall -pedantic
####################################################

queue.o: queue.c
	$(CC) $(CFLAGS) -c queue.c

clean:
	rm -f *.o